plugins {
    id 'fabric-loom' version '1.8'
    id 'java'
}

version = '1.0.0'
group = 'ru.neon'
archivesBaseName = 'neonvisuals'

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.fabricmc.net/' }
}

dependencies {
    modImplementation 'net.fabricmc:fabric-api:0.109.0+1.21.4'
}

mixins {
    add sourceSets.main, 'neonvisuals.mixins.json'
}

clientModMetadata {
    name = 'Neon Visuals'
    version = project.version
    description = 'Neon Visuals — Neon Team-Midpoint Edition'
    authors = ['Neon Team-Midpoint']
    contact = ['https://github.com/твой-репозиторий']
}
